import { describe, expect, it } from "vitest";
import { encodeBoard, encodeContext } from "./value";
import {
  canonicalizeValueTensors,
  VALUE_CANONICALIZATION,
} from "./valueCanonicalization";
import { GameState, RecentPlacement } from "./types";

const fixtureState: GameState = {
  schemaVersion: 1,
  players: [
    {
      hand: [
        { color: "blue", rankIndex: 0 },
        { color: "blue", rankIndex: 1 },
        { color: "red", rankIndex: 2 },
        { color: "green", rankIndex: 3 },
      ],
      negativeCards: [],
      lossScore: 5,
    },
    { hand: [], negativeCards: [], lossScore: 5 },
    { hand: [], negativeCards: [], lossScore: 5 },
    { hand: [], negativeCards: [], lossScore: 5 },
  ],
  board: {
    "1,0": [{ color: "red", rankIndex: 0 }],
    "1,1": [{ color: "red", rankIndex: 1 }],
    "4,2": [{ color: "green", rankIndex: 2 }],
  },
  deck: [],
  currentPlayerIndex: 1,
  phase: "refill",
  cardsPlayedThisTurn: 0,
  winners: [],
  settlementCount: 0,
  lastTurnPlayCounts: [0, 0, 0, 0],
  randomState: 0,
};

const fixtureHistory: RecentPlacement[] = [
  {
    playerIndex: 3,
    card: { color: "red", rankIndex: 1 },
    scoreDelta: 0,
    negativeCardDelta: 0,
  },
  {
    playerIndex: 0,
    card: { color: "green", rankIndex: 2 },
    scoreDelta: 1,
    negativeCardDelta: 0,
  },
];

// Generated by online_bundle/src/yellowstone/value_canonicalization.py.
const expectedContext = [
  1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0.1666666716337204, 1, 1, 0, 0,
  0, 0.3333333432674408, 1, 0, 1, 0, 0, 0.5, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0.1428571492433548, 0.6666666865348816, 0,
  0.1428571492433548, 0, 0, 0.1428571492433548, 0, 0,
  0.1428571492433548, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
  1, 1, 0, 0, 0, 0.1666666716337204, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
  0, 0.3333333432674408, 0.3333333432674408, 0,
];

describe("value input canonicalization", () => {
  it("matches the Python fast_lr_ud_color_v1 golden output", () => {
    expect(VALUE_CANONICALIZATION).toBe("fast_lr_ud_color_v1");
    const result = canonicalizeValueTensors(
      encodeBoard(fixtureState),
      encodeContext(fixtureState, 0, fixtureHistory),
    );
    const nonzeroBoard = [...result.board.entries()].filter(
      ([, value]) => value !== 0,
    );
    expect(nonzeroBoard).toEqual([
      [1, 1],
      [57, 1],
      [459, 1],
      [1373, 1],
      [1380, 1],
      [1390, 1],
    ]);
    expect([...result.context]).toEqual(expectedContext);
  });

  it("is idempotent", () => {
    const first = canonicalizeValueTensors(
      encodeBoard(fixtureState),
      encodeContext(fixtureState, 0, fixtureHistory),
    );
    const second = canonicalizeValueTensors(first.board, first.context);
    expect(second.board).toEqual(first.board);
    expect(second.context).toEqual(first.context);
  });
});
